version: '3.9'
services:
    nginx:
        image: nginx:latest
        container_name: ${APP_NAME}-nginx
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./dist:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php-fpm

    php-fpm:
        image: php:8.2-fpm
        container_name: ${APP_NAME}-php
        volumes:
            - ./dist:/var/www/html